### ISSUE TITLE
Add support for parallelism

### ISSUE THREAD

**Issue by Technolords** [Technolords/microservice-jolokia-client#5]

**Comment by Technolords** [comment]
Initial prototype shows some odd issues:

```
2017-02-27 17:22:44,171 [INFO] [Camel Thread #2 - name] [net.technolords.micro.jolokia.JolokiaClientFactory] Using connection timeout: 2500 ms
2017-02-27 17:22:44,171 [INFO] [Camel Thread #1 - name] [net.technolords.micro.jolokia.JolokiaClientFactory] Using connection timeout: 2500 ms
2017-02-27 17:22:44,259 [INFO] [Camel Thread #1 - name] [net.technolords.micro.jolokia.JolokiaClientFactory] Created client...
2017-02-27 17:22:44,259 [INFO] [Camel Thread #2 - name] [net.technolords.micro.jolokia.JolokiaClientFactory] Created client...
2017-02-27 17:22:44,298 [INFO] [Camel Thread #2 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Runtime","attribute":"VmName","type":"read"},"value":"Java HotSpot(TM) 64-Bit Server VM","timestamp":1488212564,"status":200}
2017-02-27 17:22:44,298 [INFO] [Camel Thread #1 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":536870912,"committed":676331520,"max":954728448,"used":62241104},"timestamp":1488212564,"status":200}


2017-02-27 17:22:49,156 [INFO] [Camel Thread #4 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":536870912,"committed":676331520,"max":954728448,"used":62503352},"timestamp":1488212569,"status":200}
2017-02-27 17:22:49,156 [INFO] [Camel Thread #5 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Runtime","attribute":"VmName","type":"read"},"value":"Java HotSpot(TM) 64-Bit Server VM","timestamp":1488212569,"status":200}

2017-02-27 17:22:54,156 [INFO] [Camel Thread #2 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Runtime","attribute":"VmName","type":"read"},"value":"Java HotSpot(TM) 64-Bit Server VM","timestamp":1488212574,"status":200}
2017-02-27 17:22:54,156 [INFO] [Camel Thread #6 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":536870912,"committed":676331520,"max":954728448,"used":63804064},"timestamp":1488212574,"status":200}

2017-02-27 17:22:59,154 [INFO] [Camel Thread #1 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":536870912,"committed":676331520,"max":954728448,"used":64205848},"timestamp":1488212579,"status":200}
2017-02-27 17:22:59,154 [INFO] [Camel Thread #4 - name] [net.technolords.micro.camel.processor.LogProcessor] Response: {"request":{"mbean":"java.lang:type=Runtime","attribute":"VmName","type":"read"},"value":"Java HotSpot(TM) 64-Bit Server VM","timestamp":1488212579,"status":200}

2017-02-27 17:23:04,154 [ERROR] [Camel Thread #2 - name] [net.technolords.micro.camel.processor.QueryProcessor] Unable to execute query
org.jolokia.client.exception.J4pRemoteException: Unauthorized
        at org.jolokia.client.J4pClient.extractJsonResponse(J4pClient.java:278) ~[microservice-jolokia-client-1.0.0-SNAPSHOT.jar:?]
        at org.jolokia.client.J4pClient.execute(J4pClient.java:191) ~[microservice-jolokia-client-1.0.0-SNAPSHOT.jar:?]

```
